spring:
  application:
    name: product-api

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: spring-admin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never
